name: notify
on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - closed
  issue_comment:
  push:
jobs:
  notifyPR:
    if: ${{ github.event.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: Google Chat Notification
        run: |
          curl --location --request POST '${{ secrets.WEBHOOK }}' \
          --header 'Content-Type: application/json' \
          --data-raw '{
              "cards": [
                  {
                      "header": {
                          "title": "Pull Request Tracker",
                          "subtitle": "Pull Request \"${{ github.event.pull_request.title }}\" was <b>${{ github.event.action }}</b>"
                      },
                      "sections": [
                          {
                              "widgets": [
                                  {
                                     "keyValue": {
                                          "topLabel": "User",
                                          "content": "${{ github.event.pull_request.user.login }}"
                                      },
                                  },
                                  {
                                     "textParagraph": {
                                          "text": "<a href=\"${{ github.event.pull_request.html_url }}\">${{ github.event.pull_request.html_url }}</a>"
                                      }
                                  },
                                  {
                                     "keyValue": {
                                          "topLabel": "PR number",
                                          "content":  "Issue number ${{ github.event.pull_request.number }}"
                                      }
                                  },
                                  {
                                    "textParagraph": {
                                        "text": "Pull Request is ${{ github.event.pull_request.state }}"
                                    }
                                  },
                                  {
                                    "keyValue": {
                                        "topLabel": "Draft?",
                                        "content": "${{ github.event.pull_request.draft }}"
                                    }
                                  }
                              ]
                          }
                      ]
                  }
              ],
              "thread": {
                "threadKey": "PR${{ github.event.pull_request.number }}"
              }
          }'
